name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install the ssg tool
      run: dotnet tool install terevintosoftware.staticsitegenerator.tool --global
    - name: Build
      run: dotnet build -c Release

    - name: Run the ssg tool
      run: ssg --project ${GITHUB_WORKSPACE}/src/TerevintoSoftware.StaticSiteGenerator.Demo --output ${GITHUB_WORKSPACE}/out --route-casing KebabCase --use-localization true --assembly bin/Release/net6.0/TerevintoSoftware.StaticSiteGenerator.Demo.dll

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3

    - name: Install the Netlify CLI
      run: npm install netlify-cli -g

    - name: Push to Netlify
      run: cd ./out && netlify deploy --dir . --site staticsitegenerator  --prod --auth ${{secrets.NETLIFY_TOKEN}}
